# AllCops:
#   TargetRubyVersion: 2.0
# Offense count: 1
# Cop supports --auto-correct.
Lint/Debugger:
  Exclude:
    - 'lib/pages/common.rb'

# Offense count: 6
Style/Documentation:
  Exclude:
    - 'lib/data_helper.rb'
    - 'lib/page_helper.rb'
    - 'lib/pages/game.rb'
    - 'lib/pages/generic_base_page.rb'
    - 'lib/pages/launch.rb'
    - 'lib/pages/login.rb'
    - 'lib/pages/logout.rb'
    - 'lib/pages/signup.rb'

# Offense count: 3
Metrics/AbcSize:
  Max: 58

# Offense count: 12
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes.
# URISchemes: http, https
Metrics/LineLength:
  Max: 154

# Offense count: 2
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 37

# Offense count: 5
# Configuration parameters: AllowedVariables.
Style/GlobalVars:
  Exclude:
    - 'features/support/hooks.rb'

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: IgnoredMethods.
# IgnoredMethods: respond_to
Style/SymbolProc:
  Exclude:
    - 'lib/pages/launch.rb'
    - 'lib/pages/login.rb'
