//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Roblox.Test.Client
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.watrbx.wtf/Roblox.Test", ConfigurationName="Roblox.Test.Client.IRun")]
    public interface IRun
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.watrbx.wtf/Roblox.Test/IRun/Ping", ReplyAction="http://www.watrbx.wtf/Roblox.Test/IRun/PingResponse")]
        string Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.watrbx.wtf/Roblox.Test/IRun/Execute", ReplyAction="http://www.watrbx.wtf/Roblox.Test/IRun/ExecuteResponse")]
        string Execute(string testname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.watrbx.wtf/Roblox.Test/IRun/GetHeader", ReplyAction="http://www.watrbx.wtf/Roblox.Test/IRun/GetHeaderResponse")]
        string GetHeader(string testname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.watrbx.wtf/Roblox.Test/IRun/SpawnProcess", ReplyAction="http://www.watrbx.wtf/Roblox.Test/IRun/SpawnProcessResponse")]
        string SpawnProcess(out int pid, string filename, string args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.watrbx.wtf/Roblox.Test/IRun/KillProcess", ReplyAction="http://www.watrbx.wtf/Roblox.Test/IRun/KillProcessResponse")]
        string KillProcess(int pid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.watrbx.wtf/Roblox.Test/IRun/Cleanup", ReplyAction="http://www.watrbx.wtf/Roblox.Test/IRun/CleanupResponse")]
        string Cleanup();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IRunChannel : Roblox.Test.Client.IRun, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class RunClient : System.ServiceModel.ClientBase<Roblox.Test.Client.IRun>, Roblox.Test.Client.IRun
    {
        
        public RunClient()
        {
        }
        
        public RunClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public RunClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public RunClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public RunClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string Ping()
        {
            return base.Channel.Ping();
        }
        
        public string Execute(string testname)
        {
            return base.Channel.Execute(testname);
        }
        
        public string GetHeader(string testname)
        {
            return base.Channel.GetHeader(testname);
        }
        
        public string SpawnProcess(out int pid, string filename, string args)
        {
            return base.Channel.SpawnProcess(out pid, filename, args);
        }
        
        public string KillProcess(int pid)
        {
            return base.Channel.KillProcess(pid);
        }
        
        public string Cleanup()
        {
            return base.Channel.Cleanup();
        }
    }
}
